"""empty message

Revision ID: 04833bf282ac
Revises: 13fd364f59da
Create Date: 2026-01-17 12:15:35.496297

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04833bf282ac"
down_revision: Union[str, Sequence[str], None] = "13fd364f59da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_project_sessions",
        sa.Column("title", sa.String(length=255), nullable=True, comment="会话标题"),
    )
    op.add_column(
        "ai_project_sessions",
        sa.Column("file_mtime", sa.DateTime(), nullable=True, comment="文件修改时间"),
    )
    op.add_column(
        "ai_project_sessions",
        sa.Column("file_size", sa.Integer(), nullable=True, comment="文件大小（字节）"),
    )
    op.add_column(
        "ai_project_sessions",
        sa.Column(
            "removed",
            sa.Boolean(),
            server_default="0",
            nullable=True,
            comment="是否已删除",
        ),
    )
    op.create_index(
        op.f("ix_ai_project_sessions_removed"),
        "ai_project_sessions",
        ["removed"],
        unique=False,
    )
    op.add_column(
        "ai_projects",
        sa.Column(
            "git_worktree_project",
            sa.Boolean(),
            nullable=True,
            comment="是否为 git worktree 项目",
        ),
    )
    op.add_column(
        "ai_projects",
        sa.Column(
            "git_main_project_path",
            sa.Text(),
            nullable=True,
            comment="git worktree 项目的主项目路径",
        ),
    )
    op.add_column(
        "ai_projects",
        sa.Column(
            "removed", sa.Boolean(), nullable=True, comment="项目路径是否已被移除"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_projects", "removed")
    op.drop_column("ai_projects", "git_main_project_path")
    op.drop_column("ai_projects", "git_worktree_project")
    op.drop_index(
        op.f("ix_ai_project_sessions_removed"), table_name="ai_project_sessions"
    )
    op.drop_column("ai_project_sessions", "removed")
    op.drop_column("ai_project_sessions", "file_size")
    op.drop_column("ai_project_sessions", "file_mtime")
    op.drop_column("ai_project_sessions", "title")
    # ### end Alembic commands ###
