"""empty message

Revision ID: 13fd364f59da
Revises:
Create Date: 2026-01-12 21:41:07.811427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "13fd364f59da"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_project_sessions",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="自增主键"
        ),
        sa.Column(
            "session_id", sa.String(length=255), nullable=False, comment="会话ID"
        ),
        sa.Column("project_id", sa.Integer(), nullable=False, comment="关联的项目ID"),
        sa.Column("session_file", sa.Text(), nullable=True, comment="会话文件路径"),
        sa.Column(
            "session_file_md5",
            sa.String(length=32),
            nullable=True,
            comment="会话文件MD5哈希值",
        ),
        sa.Column(
            "is_agent_session", sa.Boolean(), nullable=False, comment="是否为Agent会话"
        ),
        sa.Column(
            "ai_tool", sa.String(length=50), nullable=False, comment="AI工具类型"
        ),
        sa.Column("project_path", sa.Text(), nullable=True, comment="项目路径"),
        sa.Column(
            "git_branch", sa.String(length=255), nullable=True, comment="Git分支"
        ),
        sa.Column(
            "first_active_at", sa.DateTime(), nullable=True, comment="首次执行时间"
        ),
        sa.Column(
            "last_active_at", sa.DateTime(), nullable=True, comment="最后执行时间"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_project_sessions_project_id"),
        "ai_project_sessions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "ai_projects",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="自增主键"
        ),
        sa.Column(
            "project_name", sa.String(length=255), nullable=False, comment="项目名称"
        ),
        sa.Column("project_path", sa.Text(), nullable=True, comment="项目完整路径"),
        sa.Column(
            "claude_session_path",
            sa.Text(),
            nullable=True,
            comment="Claude session 存储路径",
        ),
        sa.Column(
            "ai_tools",
            sqlite.JSON(),
            nullable=False,
            comment="AI工具列表，JSON格式存储",
        ),
        sa.Column(
            "first_active_at", sa.DateTime(), nullable=True, comment="首次执行时间"
        ),
        sa.Column(
            "last_active_at", sa.DateTime(), nullable=True, comment="最后执行时间"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app_settings",
        sa.Column(
            "id", sa.String(length=255), nullable=False, comment="设置键名，主键"
        ),
        sa.Column("value", sa.Text(), nullable=True, comment="设置值"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_settings")
    op.drop_table("ai_projects")
    op.drop_index(
        op.f("ix_ai_project_sessions_project_id"), table_name="ai_project_sessions"
    )
    op.drop_table("ai_project_sessions")
    # ### end Alembic commands ###
