"""empty message

Revision ID: 3dca7f30d925
Revises: 04833bf282ac
Create Date: 2026-01-17 15:10:33.006382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dca7f30d925"
down_revision: Union[str, Sequence[str], None] = "04833bf282ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_projects",
        sa.Column("favorited", sa.Boolean(), nullable=True, comment="是否已收藏"),
    )
    op.add_column(
        "ai_projects",
        sa.Column("favorited_at", sa.DateTime(), nullable=True, comment="收藏时间"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_projects", "favorited_at")
    op.drop_column("ai_projects", "favorited")
    # ### end Alembic commands ###
